# Generated by Django 2.0.6 on 2018-10-23 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenseApp', '0004_auto_20181023_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensemodel',
            name='username_fk',
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
